---
groups:
  - name: cloudfoundry-sumologic-nozzle
    jobs:
    - unit-testing
    - downstream-master
    - unit-testing-master
    - tag-master
    - ship-it
  - name: master
    jobs:
    - downstream-master
    - unit-testing-master
    - tag-master
    - ship-it
  - name: develop
    jobs:
    - unit-testing



jobs:
- name: unit-testing
  public: true
  serial: true
  plan:
   - get: cloudfoundry-sumologic-nozzle-ci
     resource: cloudfoundry-sumologic-nozzle-develop
     trigger: true
   - task: unit-testing
     file: cloudfoundry-sumologic-nozzle-ci/ci/unit-testing/unit-testing.yml


- name: unit-testing-master
  public: true
  serial: true
  plan:
  - get: cloudfoundry-sumologic-nozzle-ci
    resource: cloudfoundry-sumologic-nozzle-master
    trigger: true
  - task: unit-testing
    file: cloudfoundry-sumologic-nozzle-ci/ci/unit-testing/unit-testing.yml


- name: tag-master
  public: true
  serial: true
  plan:
  - get: cloudfoundry-sumologic-nozzle-ci
    resource: cloudfoundry-sumologic-nozzle-master
    passed: [unit-testing-master]
  - put: version
    params: {bump: minor}
  - put: cloudfoundry-sumologic-nozzle-master
    params:
      only_tag: true
      repository: cloudfoundry-sumologic-nozzle-ci
      tag: version/number


- name: ship-it
  public: true
  serial: true
  plan:
  - get: cloudfoundry-sumologic-nozzle-ci
    resource: cloudfoundry-sumologic-nozzle-master
    passed: [tag-master]
    trigger: true
  - get: version
  - task: build-binary
    file: cloudfoundry-sumologic-nozzle-ci/ci/build-all/build-all.yml
    params:
      VERSION_APP: version/number
  - put: gh-release
    params :
      name: version/number
      tag: version/number
      globs:
      - cloudfoundry-sumologic-nozzle-ci-build/dist/*/*/*




- name: downstream-master
  public: true
  serial: true
  plan:
  - aggregate:
    - get: cloudfoundry-sumologic-nozzle-ci
      resource: cloudfoundry-sumologic-nozzle-develop
    - get: release-repo-master
      resource: firehouse-to-sumologic-master
      trigger: true
      passed: [tag-master]
    - get: release-repo
      resource: cloudfoundry-sumologic-nozzle-merge-target
  - task: merge-master-to-develop
    file: cloudfoundry-sumologic-nozzle-ci/ci/merge-master-to-develop/merge-master-to-develop.yml
    params:
      GIT_USERNAME: {{github-username}}
      GIT_EMAIL:  {{github-email}}




resources:
- name: cloudfoundry-sumologic-nozzle-merge-target
  type: git
  source:
    branch: develop
    private_key: {{private-key-github-concourse}}
    uri: git@github.com:cloudfoundry-community/cloudfoundry-sumologic-nozzle.git

- name: cloudfoundry-sumologic-nozzle-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/cloudfoundry-sumologic-nozzle.git
    branch: develop
    private_key: {{private-key-github-concourse}}

- name: firehouse-to-sumologic-master
  type: git
  source:
    uri: git@github.com:cloudfoundry-community/firehouse-to-sumologic.git
    branch: master
    private_key: {{private-key-github-concourse}}



- name: gh-release
  type: github-release
  source:
    user: cloudfoundry-community
    repository: cloudfoundry-sumologic-nozzle
    access_token: {{github-access-token}}

- name: version
  type: semver-gwenn
  source:
    driver: git
    uri: git@github.com:cloudfoundry-community/cloudfoundry-sumologic-nozzle.git
    branch: version
    file: version
    private_key: {{private-key-github-concourse}}
    git_user: {{concourse-user-gitinfo}}



resource_types:
- name: semver-gwenn
  type: docker-image
  source:
    repository: getourneau/semver-resource
